// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEi4PeB3GRKYGf-JMe3gkATyUHpcsaK0',
    appId: '1:140047509817:web:331c4105e8cb29bec7a0e8',
    messagingSenderId: '140047509817',
    projectId: 'bachelorexp1',
    authDomain: 'bachelorexp1.firebaseapp.com',
    databaseURL: 'https://bachelorexp1.firebaseio.com',
    storageBucket: 'bachelorexp1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ39mFn-5lK_zK7OdDEhJIAi43K628LE8',
    appId: '1:140047509817:ios:248c2d42aade70d9c7a0e8',
    messagingSenderId: '140047509817',
    projectId: 'bachelorexp1',
    databaseURL: 'https://bachelorexp1.firebaseio.com',
    storageBucket: 'bachelorexp1.appspot.com',
    androidClientId: '140047509817-2ciaook2qo3br71ht3bogp83qqrcct6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsEi4PeB3GRKYGf-JMe3gkATyUHpcsaK0',
    appId: '1:140047509817:web:331c4105e8cb29bec7a0e8',
    messagingSenderId: '140047509817',
    projectId: 'bachelorexp1',
    authDomain: 'bachelorexp1.firebaseapp.com',
    databaseURL: 'https://bachelorexp1.firebaseio.com',
    storageBucket: 'bachelorexp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ39mFn-5lK_zK7OdDEhJIAi43K628LE8',
    appId: '1:140047509817:ios:2c46f9c5bad6c28ec7a0e8',
    messagingSenderId: '140047509817',
    projectId: 'bachelorexp1',
    databaseURL: 'https://bachelorexp1.firebaseio.com',
    storageBucket: 'bachelorexp1.appspot.com',
    androidClientId: '140047509817-2ciaook2qo3br71ht3bogp83qqrcct6l.apps.googleusercontent.com',
    iosBundleId: 'com.nomba.chitchat',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wgVhcD9LH4NUy0OthI8kE1dpF0328Mo',
    appId: '1:140047509817:android:043dd35fca0e10d4c7a0e8',
    messagingSenderId: '140047509817',
    projectId: 'bachelorexp1',
    databaseURL: 'https://bachelorexp1.firebaseio.com',
    storageBucket: 'bachelorexp1.appspot.com',
  );

}